music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums, only: [:new, :create, :edit, :show, :update, :destroy]
end

music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, :live, :band_id, presence: true
  
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true
end

music_app/app/models/user.rb
class User < ApplicationRecord
  after_initialize :ensure_session_token
  validates :email, :password_digest, :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return user if user && user.is_password?(password)
    nil
  end
end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
  end

  def create
    album = Album.new(ablums_params)

    if album.save!
      redirect_to band_url(album.band_id)
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    album = Album.find(params[:id])
    if album.update!
      redirect_to band_url(album.band_id)
    else
      render :edit
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def destroy
    album = Album.find(params[:id])
    if album
      album.destroy
      redirect_to band_url(album.band_id)
    else
      redirect_to band_url(album.band_id)
    end
  end

  private

  def ablums_params
    params.require(:album).permit(:title, :year, :live, :band_id)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  protect_from_forgery with: :exception

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    return true if current_user
    nil
  end

end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    #render
    # debugger
    @bands = Band.all
    render :index
  end

  def new
    #render
  end

  def create
    #logic for creating
    band = Band.new(bands_params)

    if band.save
      redirect_to bands_url
    else
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    #render
  end


  def update
    #logic for updating
    @band = Band.find(params[:id])

    if @band.update!(bands_params)
      redirect_to bands_url
    else
      render :edit
    end
  end

  def show
    #render
    @band = Band.find(params[:id])
  end

  def destroy
    #logic for destoring
    @band = Band.find(params[:id])
    if @band
      @band.destroy
    end
    redirect_to bands_url
  end

  private

  def bands_params
    params.require(:band).permit(:name)
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if user
      log_in_user!(user)
      redirect_to user_url(user.id)
    else
      redirect_to new_session_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)

    if user.save
      log_in_user!(user)
      redirect_to user_url(user.id)
    else
      render :new
    end

  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/albums/new.html.erb
<h1>Create an Album!</h1>

<form class="" action="<%=albums_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

  <label>Title:
    <input type="text" name="album[title]" value="">
  </label>
  <br>
  <label>Year:
    <input type="text" name="album[year]" value="">
  </label>
  <br>

  <input type="submit" name="" value="Submit">
</form>

music_app/app/views/bands/edit.html.erb
<h1>Edit the band!</h1>

<form action="<%=band_url%>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Name
    <input type="text" name="band[name]" value="<%=@band.name%>">
  </label>

  <input type="submit" value="Edit!">
</form>

music_app/app/views/bands/index.html.erb
<h1>
List of Registered Bands
</h1>

<% @bands.each do |band| %>
  <li>
    <%= band.name %>
    <a href="<%=band_url(band.id)%>">bio</a>
  </li>
<% end %>

<a href=" <%= new_band_url %> ">Create new band</a>

music_app/app/views/bands/new.html.erb
<h1>Create a new band!</h1>

<form action="<%=bands_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Name
    <input type="text" name="band[name]" value="">
  </label>

  <input type="submit" value="Create!">
</form>

music_app/app/views/bands/show.html.erb
<h1>
  <%= @band.name %>
</h1>
<p>
  <a href="<%=edit_band_url(@band.id)%>">edit</a>
</p>

<form class="" action="band_url" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <input type="submit" value="delete">
</form>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <h1>Music App</h1>

    <div>
    <% unless logged_in? %>
      <a href="<%= new_user_url %>" text>Register</a>
      <a href="<%= new_session_url %>">Log In</a>
    <% else %>
      <form action="<%= session_url%>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Log out">
      </form>
    <% end %>
    </div>

  </header>

  <body>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h1>Create a New User!</h1>

<form action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Email:
    <input type="text" name="user[email]" value="">
  </label>
  <br>
  <label>Password:
    <input type="password" name="user[password]" value="">
  </label>
  <br>
  <input type="submit" value="Create">
</form>

music_app/app/views/users/show.html.erb
<h1>
  Hello, <%= @user.email %>!
</h1>